### ISSUE TITLE
Dates and days of week don't line up correctly.

### ISSUE THREAD

**Issue by mattgraham1** [megraham/FlutterCalendar#1]
Needs to implement some sort of Gregorian calendar for days of week (i.e. M-F) with the dates.

**Comment by mattgraham1** [comment]
Used Dart's DateTime class to figure out the day of the week the date landed on. Then I adjust how the month view calendar was being presented. The month view now aligns the dates with the proper day of the week.

**Comment by apos37** [comment]
Nice calendar app, Matt! I was checking it out and had the same issue here with the dates not lining up with the day of the week, but only when I first loaded the screen. I fixed this easily by adding `setMonthPadding();` to initState.
