### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by josephraj2k16** [megraham/FlutterCalendar#7]
hi,I have imported your project,and while building its shows an error of,

ProcessException: Process "C:\Users\Harivi\Downloads\FlutterCalendar-master\FlutterCalendar-master\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Harivi\Downloads\FlutterCalendar-master\FlutterCalendar-master\android\app\build.gradle' line: 43

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: C:\Users\Harivi\Downloads\FlutterCalendar-master\FlutterCalendar-master\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

this is the build.gradle file from ur project.

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.graham.calendar"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 1
        versionName "1.2"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}

apply plugin: 'com.google.gms.google-services'`

**Comment by mattgraham1** [comment]
Hi, are you sure you have the latest code. From looking at the error the build.gradle file should have the line "signingConfig signingConfigs.release" commented out. I just looked at the master branch and that line is commented out. Please try and pull the most recent code from the master branch (i.e. 'git pull origin master').
