### ISSUE TITLE
Current month data is not displaying on load sometimes

### ISSUE THREAD

**Issue by apos37** [megraham/FlutterCalendar#8]
The calendar works great, but for some reason the data shows up sometimes when I load the screen, and other times I go back to the home screen and open the calendar again and the current month's data doesn't show up. I have to click next or previous month and go back to see them when this happens. Any suggestions to get it to persist on every load? Thanks in advance...

**Comment by mattgraham1** [comment]
Hey @mrgandy I haven't been actively working on this for some time now. To be honest, it was a great deep dive into Flutter / Firebase for me. I've contemplated pulling the app and retiring it as I haven't added anything to it for so long. If I don't do that I'll take a look into the month view not refreshing, but from your details above it sounds like the OnResume() callback from Android isn't fetching the data every time. Something not in sync with the OS lifecycle callbacks would be my guess.

**Comment by apos37** [comment]
Thank you, Matt. I completely understand. It seems to be working for me now that I switched out the FutureBuilder with a StreamBuilder.
